#!/usr/bin/env bash

# polkit
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# compositor
picom --animations -b &

# Notifications
dunst &

#compton
#compton &


# Script for polybar to run in dual monitor

killall -q polybar
    while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar main &
done




